#!/usr/bin/env python3
from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parents[1]
entry = root / "include" / "thimble" / "thimble.hpp"
out = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "dist" / "thimble.hpp"
seen = set()

# Recursively inline only local Thimble headers. Standard-library includes are
# left in place, so the generated file remains a normal portable header.
def expand(path):
    path = path.resolve()
    if path in seen:
        return ""
    seen.add(path)
    text = path.read_text()
    text = re.sub(r'^\s*#pragma once\s*$', '', text, flags=re.M)
    def repl(m):
        return expand(path.parent / m.group(1))
    return re.sub(r'^\s*#include\s+"([^"]+)"\s*$', repl, text, flags=re.M)

# The output directory is created for first-time users running the script.
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("// Generated by tools/amalgamate.py; do not edit.\n#pragma once\n" + expand(entry))
print(out)
